# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_menuWindow(object):
    def setupUi(self, menuWindow):
        menuWindow.setObjectName("menuWindow")
        menuWindow.resize(600, 300)
        menuWindow.setMinimumSize(QtCore.QSize(600, 300))
        menuWindow.setMaximumSize(QtCore.QSize(600, 300))
        self.centralwidget = QtWidgets.QWidget(menuWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.title = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.title.setFont(font)
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setObjectName("title")
        self.verticalLayout.addWidget(self.title)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.button_register = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.button_register.setFont(font)
        self.button_register.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("source/5.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_register.setIcon(icon)
        self.button_register.setIconSize(QtCore.QSize(40, 40))
        self.button_register.setObjectName("button_register")
        self.horizontalLayout.addWidget(self.button_register)
        self.button_attendance = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.button_attendance.setFont(font)
        self.button_attendance.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("source/1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_attendance.setIcon(icon1)
        self.button_attendance.setIconSize(QtCore.QSize(40, 40))
        self.button_attendance.setObjectName("button_attendance")
        self.horizontalLayout.addWidget(self.button_attendance)
        self.button_management = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.button_management.setFont(font)
        self.button_management.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("source/4.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_management.setIcon(icon2)
        self.button_management.setIconSize(QtCore.QSize(40, 40))
        self.button_management.setObjectName("button_management")
        self.horizontalLayout.addWidget(self.button_management)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 80, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem)
        menuWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(menuWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 600, 21))
        self.menubar.setObjectName("menubar")
        menuWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(menuWindow)
        self.statusbar.setObjectName("statusbar")
        menuWindow.setStatusBar(self.statusbar)

        self.retranslateUi(menuWindow)
        QtCore.QMetaObject.connectSlotsByName(menuWindow)

    def retranslateUi(self, menuWindow):
        _translate = QtCore.QCoreApplication.translate
        menuWindow.setWindowTitle(_translate("menuWindow", "Menu"))
        self.title.setText(_translate("menuWindow", "人脸识别考勤系统"))
        self.button_register.setText(_translate("menuWindow", "录入信息"))
        self.button_attendance.setText(_translate("menuWindow", "考勤"))
        self.button_management.setText(_translate("menuWindow", "信息管理"))
