# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'register.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_registerWindow(object):
    def setupUi(self, registerWindow):
        registerWindow.setObjectName("registerWindow")
        registerWindow.resize(900, 700)
        registerWindow.setMinimumSize(QtCore.QSize(900, 700))
        registerWindow.setMaximumSize(QtCore.QSize(900, 700))
        self.centralwidget = QtWidgets.QWidget(registerWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_register_show = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_register_show.setFont(font)
        self.label_register_show.setAlignment(QtCore.Qt.AlignCenter)
        self.label_register_show.setObjectName("label_register_show")
        self.verticalLayout_2.addWidget(self.label_register_show)
        self.text_register_out = QtWidgets.QTextBrowser(self.groupBox)
        self.text_register_out.setMaximumSize(QtCore.QSize(16777215, 100))
        self.text_register_out.setReadOnly(True)
        self.text_register_out.setObjectName("text_register_out")
        self.verticalLayout_2.addWidget(self.text_register_out)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.button_register_start = QtWidgets.QPushButton(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.button_register_start.setFont(font)
        self.button_register_start.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("source/start_registration.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_register_start.setIcon(icon)
        self.button_register_start.setIconSize(QtCore.QSize(30, 30))
        self.button_register_start.setObjectName("button_register_start")
        self.horizontalLayout.addWidget(self.button_register_start)
        self.button_register_cancel = QtWidgets.QPushButton(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.button_register_cancel.setFont(font)
        self.button_register_cancel.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("source/back.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_register_cancel.setIcon(icon1)
        self.button_register_cancel.setIconSize(QtCore.QSize(30, 30))
        self.button_register_cancel.setObjectName("button_register_cancel")
        self.horizontalLayout.addWidget(self.button_register_cancel)
        self.verticalLayout.addWidget(self.groupBox_2)
        registerWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(registerWindow)
        self.statusbar.setObjectName("statusbar")
        registerWindow.setStatusBar(self.statusbar)

        self.retranslateUi(registerWindow)
        QtCore.QMetaObject.connectSlotsByName(registerWindow)

    def retranslateUi(self, registerWindow):
        _translate = QtCore.QCoreApplication.translate
        registerWindow.setWindowTitle(_translate("registerWindow", "MainWindow"))
        self.label.setText(_translate("registerWindow", "录入人脸信息"))
        self.groupBox.setTitle(_translate("registerWindow", "显示区域"))
        self.label_register_show.setText(_translate("registerWindow", "暂无信号输入"))
        self.groupBox_2.setTitle(_translate("registerWindow", "操作区"))
        self.button_register_start.setText(_translate("registerWindow", "开始录入"))
        self.button_register_cancel.setText(_translate("registerWindow", "返回主界面"))
